FROM alpine:latest

RUN apk update
RUN apk add mc git tmux
RUN apk add build-base cmake automake autoconf libtool pkgconf coreutils curl unzip gettext-tiny-dev

WORKDIR /root
RUN git clone https://github.com/neovim/neovim


