FROM nvim_common:latest

ARG ROOT_PASSWORD
ARG RUSTUSER_PASSWORD

RUN apk --update add --no-cache openssh

RUN rm -rf /var/cache/apk/*                                                  \
 && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config   \
 && sed -ie 's/#Port 22/Port 22/g' /etc/ssh/sshd_config

RUN echo "root:${ROOT_PASSWORD}" | chpasswd

RUN /usr/bin/ssh-keygen -A                                      \
 && ssh-keygen -t rsa -b 4096 -f  /etc/ssh/ssh_host_key         \
 && adduser rustuser --disabled-password                        \
 && echo "rustuser:${RUSTUSER_PASSWORD}" | chpasswd

COPY .profile /home/rustuser   
COPY .vimrc   /home/rustuser
COPY init.vim /home/rustuser/.config/nvim/

RUN chown rustuser:rustuser /home/rustuser/.profile
RUN chown rustuser:rustuser -R /home/rustuser/.config

RUN cd /home/rustuser                 \
 && chown rustuser:rustuser .profile  \
 && chown rustuser:rustuser .vimrc


USER rustuser

RUN sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
#RUN nvim +PlugInstall +qa
#RUN nvim --help

#RUN git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
#RUN vim +PluginInstall +qa

USER root
