FROM nvim_common:latest

ARG ROOT_PASSWORD
ARG RUSTUSER_PASSWORD

RUN apk --update add --no-cache openssh

RUN rm -rf /var/cache/apk/*                                                  \
 && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config   \
 && sed -ie 's/#Port 22/Port 22/g' /etc/ssh/sshd_config

RUN echo "root:${ROOT_PASSWORD}" | chpasswd

RUN /usr/bin/ssh-keygen -A                                      \
 && ssh-keygen -t rsa -b 4096 -f  /etc/ssh/ssh_host_key         \
 && adduser rustuser --disabled-password                        \
 && echo "rustuser:${RUSTUSER_PASSWORD}" | chpasswd

ADD .profile /home/rustuser
ADD init.vim /home/rustuser/.config/nvim/

RUN chown rustuser:rustuser /home/rustuser/.profile
RUN chown rustuser:rustuser -R /home/rustuser/.config



