FROM alpine:latest

ARG ROOT_PASSWORD
ARG RUSTUSER_PASSWORD

RUN apk update
RUN apk add mc git tmux
RUN apk add build-base cmake automake autoconf libtool pkgconf coreutils curl unzip gettext-tiny-dev

RUN git clone https://github.com/neovim/neovim  \
 && cd neovim                                   \ 
 && git checkout v0.5.1                         \
 && make -j4                                    
RUN make install

RUN apk --update add --no-cache openssh

RUN rm -rf /var/cache/apk/*                                                  \
 && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config   \
 && sed -ie 's/#Port 22/Port 22/g' /etc/ssh/sshd_config

RUN echo "root:${ROOT_PASSWORD}" | chpasswd

RUN /usr/bin/ssh-keygen -A                                      \
 && ssh-keygen -t rsa -b 4096 -f  /etc/ssh/ssh_host_key         \
 && adduser rustuser --disabled-password                        \
 && echo "rustuser:${RUSTUSER_PASSWORD}" | chpasswd

ADD .profile /home/rustuser
ADD init.vim /home/rustuser/.config/nvim/

#RUN ls -lah /home/rustuser
#RUN ls -lah /home/rustuser/.config/

RUN cd /home/rustuser                       \
 && mkdir -p .local/bin                     \
 && mkdir -p .config/nvim                   \
 && chown rustuser:rustuser -R .local       \
 && chown rustuser:rustuser -R .config      \
 && chown rustuser:rustuser .profile

#RUN ls -lah /home/rustuser
#RUN ls -lah /home/rustuser/.config/

RUN apk add rustup
RUN rustup-init -y
ENV PATH "/root/.cargo/bin:$PATH"

RUN ls -lah $HOME/.cargo/env
RUN source $HOME/.cargo/env
RUN cargo --version

RUN cd /home/rustuser                                                        \
 && git clone https://github.com/rust-analyzer/rust-analyzer.git             \
 && chown rustuser:rustuser -R rust-analyzer

RUN cd /home/rustuser/rust-analyzer
RUN cargo xtask install --server

RUN chown rustuser:rustuser -R /home/rustuser/rust-analyzer


ADD entry.sh /usr/local/bin

EXPOSE 22 8080

ENTRYPOINT ["entry.sh"]
CMD ["/usr/sbin/sshd","-D"]



