FROM alpine:latest

ADD .profile /root

RUN apk update
RUN apk add mc git tmux curl
RUN apk add build-base cmake automake autoconf libtool pkgconf coreutils curl unzip gettext-tiny-dev
RUN apk add neovim vim
RUN apk add rustup
RUN apk add mc

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=1.57.0

RUN rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION
RUN chmod -R a+w $RUSTUP_HOME $CARGO_HOME
#RUN source $CARGO_HOME/env









